### ISSUE TITLE
Consider moving to GNU ELPA ?

### ISSUE THREAD

**Issue by phil-s** [DamienCassou/hierarchy#48]
I see that the Installation instruction says to use MELPA.  The library does not appear to have any dependencies on other non-GNU packages, though, so would you consider instead adding this to GNU ELPA?  It seems like a neat general-purpose library, so it would be nice if there weren't any barriers to including it in Emacs in the future.

**Comment by DamienCassou** [comment]
phil-s <notifications@github.com> writes:

> I see that the Installation instruction says to use MELPA.  The 
> library does not appear to have any dependencies on other 
> non-GNU packages, though, so would you consider instead adding 
> this to GNU ELPA?


why not both MELPA and ELPA then? I put it on MELPA because I know 
how it works and this is simple. Also updates are automatic. I 
could put it on ELPA too, but I don't really see the advantage of 
doing that. What would be the benefits?


> It seems like a neat general-purpose library, so it would be 
> nice if there weren't any barriers to including it in Emacs in 
> the future. 

My view is that Emacs should get smaller by externalizing 
currently included packages, not larger :-). But even if inclusion 
is desired (I have nothing against that, my auth-password-store 
library just got included), how would the presence in ELPA help 
it?

Please note that I'm not debating for the sake of it, I really 
want to understand. I would be happy to put hierarchy on ELPA if I 
see a, even small, benefit.

Thanks for your interest 

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by phil-s** [comment]
Sure, there are definitely benefits:

1. The GNU ELPA package archive is configured in Emacs by default, whereas MELPA is not, so it will "just work" out of the box for all Emacs users.

2. GNU ELPA packages are covered by FSF copyright assignment, and therefore those packages are candidates for inclusion in Emacs (and obviously you're not convinced that's sensible at the moment; but keeping the option open is better than not).

3. Regardless of #2, GNU ELPA packages can be used as dependencies by *other* GNU ELPA packages(!!!).

Even if you don't see a reason for your package to be included as part of the default Emacs distribution, I think #3 is significant. It's really the difference between MELPA packages being able to use your package as a dependency, and ALL packages being able to use your package as a dependency.

My slightly negative view of the likes of MELPA is mostly on account of the tremendous ease with which an author can unwittingly accept patches from people who have not completed FSF copyright assignments papers. Once that occurs, a package may no longer be a viable candidate as a GNU ELPA/Emacs package at all, or it may be difficult to regain that status -- I feel that retrospectively dealing with copyright assignment for contributors is a *much* bigger pain than starting out in the desired state and not deviating from it in the first place.

**Comment by DamienCassou** [comment]
- your point 1. does not convince me as hierarchy is not for new users but for Emacs developers who probably have melpa configured
- your point 2. does not convince me either as my [auth-password-store](https://github.com/DamienCassou/auth-password-store) project has always been on MELPA and still got integrated in Emacs
- your point 3. convinces me completely :-)

**Comment by DamienCassou** [comment]
I just sent a request on emacs-devel@gnu.org mailing list.

**Comment by phil-s** [comment]
Thanks for following this up, Damien. The mailing list discussion looks very promising.

**Comment by DamienCassou** [comment]
I'm closing this issue now. It seems Emacs maintainers want hierarchy to be part of Emacs core. https://lists.gnu.org/archive/html/emacs-devel/2017-10/msg00624.html
