### ISSUE TITLE
Lost dash in item symbol

### ISSUE THREAD

**Issue by casouri** [DamienCassou/hierarchy#74]
```elisp
(let ((tree (hierarchy-new))
        (parent-fn (lambda (face)
                     (face-attribute face :inherit nil 'default))))
    (dolist (face (face-list))
      (hierarchy-add-tree tree face parent-fn)))
```

errors with `(error "Invalid face" gnus-groupnews-1-empty)`. From the surface, all I can tell is that the dash between "group" and "news" in `gnus-group-news-1-empty` is lost due to unknown reason.

I suspect the problem is in hierarchy.el because following code returns sucessffully:
```elisp
(mapcar (lambda (face)
          (face-attribute face :inherit nil 'default))
        (face-list))
```

(what did you do to my baby symbol? ;-)

**Comment by DamienCassou** [comment]
Hi @casouri,

thanks for your report. The difference I see between the hierarchy code and the mapcar code is that in the first, the code considers that the return value of `face-attribute` should be a face that will later be passed as first parameter of `face-attribute`. In the second code, the return value of `face-attribute` can be whatever. Basically, the first code is closer to:

```emacs
(mapcar (lambda (face)
          (let ((parent-face (face-attribute face :inherit nil 'default)))
            (when parent-face
              (face-attribute parent-face :inherit nil 'default))))
        (face-list))
```

which shows the same problem as the first code.

Through bisection, I found out that some faces have a broken `:inherit` value. To find them all, execute this code:

```emacs
(seq-filter (lambda (face)
              (let ((parent-face (face-attribute face :inherit nil 'default)))
                (and (not (null parent-face))
                     (not (facep parent-face)))))
            (face-list))
```

To create a hierarchy, you have to take care of that fact:

```emacs
(let ((tree (hierarchy-new))
      (parent-fn (lambda (face)
                   (let ((parent-face (face-attribute face :inherit nil 'default)))
                     ;; only add real faces to the hierarchy:
                     (when (facep parent-face)
                       parent-face)))))
  (dolist (face (face-list) tree)
    (hierarchy-add-tree tree face parent-fn))
```

This works but returns a hierarchy with many roots because the absence of an `:inherit` key means "don't inherit" instead of "inherit from default face". This might be ok depending on your use case. Nevertheless, some of hierarchy display functions only display the first root (see how `hierarchy-map-tree` takes care of a nil `ITEM`) so you won't get what you want if you use those.

One way to workaround that is to add a fake `face-root` face:

```emacs
(let ((tree (hierarchy-new))
      (parent-fn (lambda (face)
                   (let ((parent-face (if (eq face 'root-face)
                                          nil ;; the root has no parent
                                        (or (face-attribute face :inherit nil 'default)
                                            'root-face ))))
                     (cond ((facep parent-face) parent-face)
                           ((null parent-face) nil)
                           (t 'root-face))))))
  (dolist (face (face-list) tree)
    (hierarchy-add-tree tree face parent-fn)))
```

This code makes it so that only `root-face` has no parent in the hierarchy. You can then display your hierarchy as a tree widget:

```emacs
(hierarchy-tree-display tree (lambda (face _) (insert (format "%s" face))))
```

![2019-07-22-114514_491x420_scrot](https://user-images.githubusercontent.com/217543/61623084-5002f400-ac76-11e9-822e-b6b4eb552b55.png)

You can use `hierarchy-add-trees` instead of `hierarchy-add-tree` which does the `dolist` for you.

**Comment by casouri** [comment]
Thank you for your detailed explanation! You made it really clear :smile:

> This might be ok depending on your use case. 

Yes, that's ok for me because I just want to know the (possible) dependencies between faces.

**Comment by DamienCassou** [comment]
I referenced this thread in the README and added the example to the `examples/` directory: https://github.com/DamienCassou/hierarchy#faces-hierarchy-example.
